# Generated by Django 3.2 on 2021-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy_products',
            new_name='Allergies_products',
        ),
        migrations.RenameModel(
            old_name='Nutritions',
            new_name='Nutrition',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='korean_name',
            field=models.CharField(max_length=100),
        ),
    ]
