# Generated by Django 3.2 on 2021-04-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210428_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergies_products',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergies_products',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='english_name',
            new_name='en_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='korean_name',
            new_name='ko_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nutrition_id',
            new_name='nutrition',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='size_fluid_ounce',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='size_ml',
        ),
    ]
